import type { OperationScope } from './types';

const previewScope: OperationScope = {
  dateFrom: '2026-05-21',
  dateTo: '2026-06-23',
  storeName: 'FT-US-US',
  marketplaceCode: 'US',
  asin: 'B0GTTJFQTM',
  batchId: 'batch_preview_20260625',
  currency: 'USD',
};

const previewReportOptions = [
  ['campaign', '广告活动报告', 34],
  ['ad_group', '广告组报告', 220],
  ['placement', '广告位报告', 110],
  ['advertised_product', '广告（推广的商品）报告', 240],
  ['auto_targeting', '自动投放报告', 180],
  ['keyword', '关键词报告', 360],
  ['product_targeting', '商品投放报告', 270],
  ['user_search_term', '用户搜索词报告', 465],
].map(([type, label, importedRows]) => ({
  type,
  label,
  status: 'imported',
  realFileAvailable: true,
  importedRows,
}));

const previewProducts = [
  {
    id: 'preview-B0GTTJFQTM',
    asin: 'B0GTTJFQTM',
    title: 'D6',
    parent_asin: '',
    parentAsin: '',
    msku: 'D6-M',
    sku: 'D6-SKU',
    store_name: 'FT-US-US',
    marketplace_code: 'US',
    product_stage: 'keyword_exploration',
    productStage: 'keyword_exploration',
    status: 'active',
    updated_at: '2026-06-24',
    updatedAt: '2026-06-24',
    cost: {
      purchaseCost: 15.7,
      firstLegCost: 0,
      fbaFee: 6.49,
      referralFeeRate: 0.15,
      storageFee: 0,
      otherCost: 0,
      currentPrice: 49.99,
      minPrice: 33.99,
      targetNetMargin: 0.15,
      targetAcos: 0.35,
      targetTacos: 0.12,
    },
  },
  {
    id: 'preview-B0GVRW2HPY',
    asin: 'B0GVRW2HPY',
    title: 'D7',
    msku: 'D7-M',
    sku: 'D7-SKU',
    store_name: 'FT-US-US',
    marketplace_code: 'US',
    product_stage: 'scaling',
    productStage: 'scaling',
    status: 'active',
    updated_at: '2026-06-24',
    updatedAt: '2026-06-24',
    cost: { currentPrice: 49.99, targetAcos: 0.28, targetTacos: 0.1, targetNetMargin: 0.18 },
  },
  {
    id: 'preview-B0GVS5LVK2',
    asin: 'B0GVS5LVK2',
    title: 'D8',
    msku: 'D8-M',
    sku: 'D8-SKU',
    store_name: 'FT-US-US',
    marketplace_code: 'US',
    product_stage: 'declining_repair',
    productStage: 'declining_repair',
    status: 'watch',
    updated_at: '2026-06-24',
    updatedAt: '2026-06-24',
    cost: { currentPrice: 39.99, targetAcos: 0.45, targetTacos: 0.18, targetNetMargin: 0.08 },
  },
];

const previewDiagnostics = [
  {
    campaignName: 'D6-精准-核心长尾',
    adGroupName: 'SP-01',
    asin: 'B0GTTJFQTM',
    objectType: 'keyword',
    objectName: 'door lock bedroom',
    spend: 111.54,
    sales: 49.99,
    orders: 1,
    clicks: 98,
    acos: 2.231,
    cvr: 0.0102,
    cpc: 1.14,
    quantStatus: 'waste',
    lifecycleStage: 'testing',
    severity: 'high',
    recommendedAction: '降价或否定',
    diagnosis: '花费偏高且转化不足',
    suggestedDirection: '先复核再降价',
  },
  {
    campaignName: 'D6-手动精准',
    adGroupName: 'SP-02',
    asin: 'B0GTTJFQTM',
    objectType: 'search_term',
    objectName: 'smart lock',
    spend: 39.68,
    sales: 99.98,
    orders: 2,
    clicks: 45,
    acos: 0.397,
    cvr: 0.044,
    cpc: 0.88,
    quantStatus: 'watch',
    lifecycleStage: 'testing',
    severity: 'medium',
    recommendedAction: '观察',
    diagnosis: '有订单但 ACOS 偏高',
    suggestedDirection: '观察',
  },
];

const previewTimelines = Array.from({ length: 34 }, (_, index) => ({
  objectKey: `preview-${index}`,
  objectType: index % 2 ? 'search_term' : 'keyword',
  objectName: index % 2 ? 'door lock bedroom' : 'smart lock',
  asin: 'B0GTTJFQTM',
  campaignName: index % 2 ? 'D6-精准-核心长尾' : 'D6-手动精准',
  adGroupName: 'SP-01',
  dateFrom: previewScope.dateFrom,
  dateTo: previewScope.dateTo,
  daysActive: 34,
  lifecycleStage: 'testing',
  quantStatus: index % 5 === 0 ? 'waste' : index % 3 === 0 ? 'scale' : 'watch',
  recommendedAction: '复核',
  recommendedValue: '保持',
  trend: { spend: 'up', sales: index % 2 ? 'down' : 'up' },
  totals: {
    impressions: 800 + index * 20,
    clicks: 10 + index,
    cost: 5 + index,
    orders: index % 4,
    sales: (index % 4) * 49.99,
    acos: index % 4 ? 0.45 : 0,
    cpc: 1.2,
    cvr: 0.04,
    currency: 'USD',
  },
  thresholds: { targetAcos: 0.35 },
  reasons: ['浏览器预览数据，不写入数据库'],
  reviewRequired: true,
}));

const previewEvents = [
  {
    id: 'preview-event-1',
    eventDate: '2026-06-18',
    eventType: 'listing_change',
    title: 'Listing 标题优化',
    description: '补充核心词和场景词',
    asin: 'B0GTTJFQTM',
    impact: 'watch',
    createdAt: '2026-06-18T09:00:00Z',
  },
];

const previewDailyHistory = Array.from({ length: 34 }, (_, index) => {
  const date = new Date(`${previewScope.dateFrom}T00:00:00Z`);
  date.setUTCDate(date.getUTCDate() + index);
  const cost = Number((12 + (index % 6) * 3.4 + (index > 22 ? 8 : 0)).toFixed(2));
  const orders = index % 5 === 0 ? 0 : index % 4;
  const sales = Number((orders * 49.99).toFixed(2));
  const clicks = 8 + (index % 9) * 3;
  return {
    date: date.toISOString().slice(0, 10),
    impressions: 680 + index * 18,
    clicks,
    cost,
    orders,
    sales,
    acos: sales > 0 ? cost / sales : 0,
    cpc: clicks > 0 ? cost / clicks : 0,
    cvr: clicks > 0 ? orders / clicks : 0,
    currency: 'USD',
  };
});

function previewPipeline() {
  return {
    scope: previewScope,
    generatedAt: new Date().toISOString(),
    collection: {
      status: 'ready',
      latestBatch: {
        id: previewScope.batchId,
        status: 'ready',
        dateStart: previewScope.dateFrom,
        dateEnd: previewScope.dateTo,
        storeName: previewScope.storeName,
        marketplaceCode: previewScope.marketplaceCode,
        downloadDir: 'D:/preview/reports',
        manifestPath: 'D:/preview/manifest.json',
        completedAt: '2026-06-24T09:00:00Z',
      },
      sourceBatchIds: [previewScope.batchId],
      availableBatches: [{
        id: previewScope.batchId,
        status: 'ready',
        dateStart: previewScope.dateFrom,
        dateEnd: previewScope.dateTo,
        storeName: previewScope.storeName,
        marketplaceCode: previewScope.marketplaceCode,
        downloadDir: 'D:/preview/reports',
        manifestPath: 'D:/preview/manifest.json',
        totalFileRecords: 8,
        realReportFileCount: 8,
        importedRowCount: 1879,
        missingReportLabels: [],
      }],
      reportOptions: previewReportOptions,
      realReportFiles: previewReportOptions.map((item) => ({
        id: `preview-file-${item.type}`,
        reportType: item.type,
        displayName: item.label,
        status: 'imported',
        filePath: `D:/preview/reports/${item.type}.xlsx`,
        folderPath: 'D:/preview/reports',
        fileName: `${item.type}.xlsx`,
        fileSizeBytes: 1024,
        importedRows: item.importedRows,
      })),
      evidencePaths: [{ label: '浏览器预览报表目录', path: 'D:/preview/reports', kind: 'folder' }],
      fileAudit: {
        totalFileRecords: 8,
        downloadedFileRecords: 8,
        existingFileRecords: 8,
        realReportFileCount: 8,
        importedRowCount: 1879,
        rejectedEvidenceFileCount: 0,
        missingReportLabels: [],
        downloadDir: 'D:/preview/reports',
        manifestPath: 'D:/preview/manifest.json',
      },
      blockers: [],
      audit: {
        databaseReady: true,
        acceptedExtensions: ['.xlsx', '.xls', '.csv'],
        rejectedEvidenceExtensions: ['.json', '.png', '.html'],
        notes: ['浏览器预览数据只用于 UI 验证，不会写入本地数据库。'],
      },
    },
    quant: {
      hasImportedMetrics: true,
      importedRows: 1879,
      canonicalRows: 1879,
      actionableRows: 1621,
      breakdownRows: 34,
      summarySource: 'browser-preview',
      totalSpend: 784.31,
      totalSales: 1289.68,
      totalOrders: 25,
      totalClicks: 495,
      totalImpressions: 27199,
      acos: 0.6081,
      cvr: 0.0505,
      cpc: 1.58,
      wastedSpend: 403.47,
      highRiskCount: previewDiagnostics.length,
      adObjectTimelines: previewTimelines,
      diagnostics: previewDiagnostics,
      blockers: [],
    },
    operations: { events: previewEvents, eventCount: previewEvents.length, notes: [] },
    productContext: { products: previewProducts, productCount: previewProducts.length, notes: [] },
    productHistory: {
      ledgers: [{
        asin: 'B0GTTJFQTM',
        storeName: previewScope.storeName,
        marketplaceCode: previewScope.marketplaceCode,
        dateFrom: previewScope.dateFrom,
        dateTo: previewScope.dateTo,
        activeDays: previewDailyHistory.length,
        firstMetricDate: previewDailyHistory[0]?.date,
        lastMetricDate: previewDailyHistory[previewDailyHistory.length - 1]?.date,
        inferredStage: 'testing',
        stageReasons: ['浏览器预览日级广告账本，用于验证 UI，不写入数据库。'],
        daily: previewDailyHistory,
        totals: {
          impressions: previewDailyHistory.reduce((sum, day) => sum + day.impressions, 0),
          clicks: previewDailyHistory.reduce((sum, day) => sum + day.clicks, 0),
          cost: previewDailyHistory.reduce((sum, day) => sum + day.cost, 0),
          orders: previewDailyHistory.reduce((sum, day) => sum + day.orders, 0),
          sales: previewDailyHistory.reduce((sum, day) => sum + day.sales, 0),
          acos: 0.608,
          cpc: 1.58,
          cvr: 0.0505,
          currency: 'USD',
        },
        events: previewEvents,
        product: {
          productStage: 'keyword_exploration',
          targetAcos: 0.35,
          targetTacos: 0.12,
          targetNetMargin: 0.15,
          minPrice: 33.99,
        },
      }],
    },
  };
}

export function createBrowserPreviewElectronApi(username: string) {
  const recommendations = previewDiagnostics.map((diagnostic, index) => ({
    id: `preview-rec-${index + 1}`,
    batchId: previewScope.batchId,
    asin: diagnostic.asin,
    entityType: diagnostic.objectType,
    entityName: diagnostic.objectName,
    campaignName: diagnostic.campaignName,
    adGroupName: diagnostic.adGroupName,
    actionType: index === 0 ? 'decrease_bid' : 'watch',
    currentValue: '1.20',
    suggestedValue: index === 0 ? '0.95' : '1.20',
    reason: diagnostic.diagnosis,
    riskLevel: diagnostic.severity,
    status: index === 0 ? 'ready_for_approval' : 'draft',
    approvalStatus: index === 0 ? 'pending' : 'not_submitted',
    evidenceRefs: ['preview:metric', 'preview:timeline'],
    createdAt: '2026-06-24T09:00:00Z',
    updatedAt: '2026-06-24T09:00:00Z',
  }));

  return {
    getState: async () => ({
      isLoggedIn: true,
      currentStore: username || 'SHC001',
      loginSession: { erpSessionReused: true, adsEntryMode: 'browser-preview', adsTitle: '浏览器预览模式' },
    }),
    browserLogout: async () => true,
    getOperationScope: async () => previewScope,
    saveOperationScope: async () => previewScope,
    getBusinessUiDataPipeline: async () => previewPipeline(),
    getProducts: async () => previewProducts,
    saveProductConfig: async (input: unknown) => ({ ok: true, input }),
    listOperationEvents: async () => previewEvents,
    createOperationEvent: async (input: unknown) => ({ id: 'preview-event-new', input }),
    deleteOperationEvent: async () => ({ ok: true }),
    getRecommendations: async () => recommendations,
    generateRecommendations: async () => ({ generated: recommendations.length, recommendations }),
    approveRecommendation: async () => ({ ok: true }),
    rejectRecommendation: async () => ({ ok: true }),
    getBusinessKeywordOpportunities: async () => previewTimelines.map((item, index) => ({
        asin: item.asin,
        portfolioName: '预览组合',
        keyword: item.objectName,
        entityType: item.objectType,
        campaignName: item.campaignName,
        adGroupName: item.adGroupName,
        coverageStatus: index % 3 === 0 ? '未覆盖' : index % 3 === 1 ? '已覆盖' : '需补入 Listing',
        spend: item.totals.cost,
        sales: item.totals.sales,
        orders: item.totals.orders,
        clicks: item.totals.clicks,
        acos: item.totals.acos,
        opportunityLevel: index % 4 === 0 ? 'high' : index % 4 === 1 ? 'medium' : 'low',
        recommendedPlacement: index % 2 ? '五点' : '标题',
        risk: item.totals.orders > 0 ? '可带入 Listing 覆盖复核' : '有点击未出单，先复核投放风险',
        sourceFile: `D:/preview/reports/${item.objectType}.xlsx`,
      })),
    getRuleConfig: async () => ({ targetAcos: 0.35, highAcosThreshold: 0.4, minSpend: 10, noOrderClickThreshold: 30 }),
    getSettings: async () => ({ ai: { provider: 'deepseek', model: 'deepseek-v4-flash', baseUrl: 'https://api.deepseek.com' } }),
    getDeliveryReadiness: async () => ({ available: true, appReady: false, manifestDriven: true, blockers: ['浏览器预览不代表最终交付'] }),
    getDeliveryEvidenceStatus: async () => ({ ready: false, missing: ['readback'] }),
    getScheduledTasks: async () => [{ name: 'daily-import-preview', enabled: true, cron: '0 9 * * *', lastStatus: 'success' }],
    setTaskEnabled: async () => ({ ok: true }),
    runTaskNow: async () => ({ ok: true }),
    openReportPath: async () => true,
    exportDataReconciliation: async () => ({ ok: true, path: 'D:/preview/reconciliation.xlsx' }),
  };
}
