export const PAGE_HEADER_TITLES = {
  dashboard: '今日看板',
  productManagement: '产品管理',
  operationScope: '工作范围',
  dataCollection: '批量数据采集',
  dataImportValidation: '指标核验入库',
  operationEvents: '运营事件标记',
  productConfig: '产品 ACOS 配置',
  adQuant: '量化诊断中心',
  recommendations: '优化建议草案',
  approval: '审批历史中心',
  readback: '渐进执行回读',
  keywordOpportunities: '关键词机会矩阵',
  listingOptimization: 'Listing 结构重写',
  delivery: '最终验收就绪门',
  scheduler: '本地定时调度',
  settings: 'AI 适配与诊断',
} as const;
