export const PAGE_HEADER_TITLES = {
  dashboard: '今日看板',
  productManagement: '产品管理',
  operationScope: '工作范围',
  dataCollection: '数据采集',
  dataImportValidation: '导入校验',
  operationEvents: '运营事件',
  productConfig: '成本目标',
  adQuant: '广告表现',
  recommendations: '优化建议',
  approval: '审批中心',
  readback: '结果核对',
  keywordOpportunities: '关键词机会',
  listingOptimization: 'Listing草案',
  delivery: '交付验收',
  scheduler: '自动任务',
  settings: 'AI与规则',
} as const;
